# Generated by Django 5.0.1 on 2024-01-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
